[project]
name = "pythonproject25"
version = "0.1.0"
description = ""
authors = [
    {name = "Ivan",email = "ivan@example.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.flake8]
max-line-length = 79
exclude = [
    ".venv",
    "__pycache__",
    ".git",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
